# Generated by Django 5.0.1 on 2024-02-03 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_vnuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vnuser',
            name='userpass',
        ),
        migrations.RemoveField(
            model_name='vnuser',
            name='userpass2',
        ),
        migrations.AddField(
            model_name='vnuser',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vnuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='vnuser',
            name='comments',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vnuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='vnuser',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vnuser',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
